# Generated by Django 4.2.5 on 2023-11-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmovieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=12, upload_to='galary'),
            preserve_default=False,
        ),
    ]
